// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var a = 1;
var b = 2;

for (var i = 1; i < 10; i++) {
  i = a + b;
  a = b + i;
  b = i + a;

  if
}

// step 1 - add previous two numbers together
// step 2 - push to the array
// step 3 - loop through array and push evens to new array
// step 4 - sum this new even array.

// var fibEvenArray = [2]
var fibArray = [1, 2]
for (i = 1; fibArray[i] <= 4000000; i++) {
  var newNum = fibArray[i] + fibArray[i-1];
  fibArray.push(newNum);
}
console.log(fibArray);
var evenSum = 0;
for (i = 1; fibArray[i] <= 4000000; i = i + 3) {
  evenSum += fibArray[i];
}
console.log(evenSum);
